from fpdf import FPDF
import os

class PDF(FPDF):
    def header(self):
        # Logo
        # self.image('logo.png', 10, 8, 33)
        # Arial bold 15
        self.set_font('Arial', 'B', 15)
        # Move to the right
        self.cell(80)
        # Title
        self.cell(30, 10, 'Parent Eye Project Report', 0, 0, 'C')
        # Line break
        self.ln(20)

    def footer(self):
        # Position at 1.5 cm from bottom
        self.set_y(-15)
        # Arial italic 8
        self.set_font('Arial', 'I', 8)
        # Page number
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')

    def chapter_title(self, num, label):
        # Arial 12
        self.set_font('Arial', 'B', 12)
        # Background color
        self.set_fill_color(200, 220, 255)
        # Title
        self.cell(0, 6, 'Chapter %d : %s' % (num, label), 0, 1, 'L', 1)
        # Line break
        self.ln(4)

    def chapter_body(self, body):
        # Read text file
        # Times 12
        self.set_font('Times', '', 12)
        # Output justified text
        self.multi_cell(0, 5, body)
        # Line break
        self.ln()

    def add_section(self, title, body):
        self.add_page()
        self.chapter_title(self.section_counter, title)
        self.chapter_body(body)
        self.section_counter += 1

pdf = PDF()
pdf.alias_nb_pages()
pdf.section_counter = 1

# Content
content = {
    "Project Overview": """Parent Eye is a web application designed to bridge the gap between schools and parents, particularly those who may not be fluent in English. It provides a real-time dashboard of student performance, attendance, and notifications, accessible in multiple Indian languages (English, Telugu, Hindi, Tamil).\n
The core innovation lies in its AI capabilities during the project:
- Performance Prediction: Uses machine learning to predict future marks based on historical trends.
- Multilingual Chatbot: An intelligent assistant that answers parent queries in their native language.""",

    "Technology Stack": """1. Backend:
- Python 3.x with Flask Web Server
- AI/ML: scikit-learn (Linear Regression), numpy
- NLP: deep_translator (Google Translate), gTTS (Text-to-Speech)
- Utilities: flask-cors

2. Frontend:
- HTML5, CSS3, Vanilla JavaScript (ES6+)
- Visualization: Chart.js
- Voice: Web Speech API for speech recognition

3. Data Storage:
- In-memory Python dictionaries simulating a database structure for Parents, Students, Marks, and Notifications.""",

    "Key Features": """A. Multilingual Support
- Supports English, Telugu, Hindi, and Tamil.
- Static UI translations + Dynamic content translation via Google Translate API.

B. AI-Powered Dashboard
- Marks Visualization with color-coded indicators.
- Trend Analysis using Line Charts.
- Prediction Engine forecasting next semester marks with confidence scores.

C. Chat Assistant
- Context-aware chatbot (knows student's specific marks).
- Voice-enabled (Speech-to-Text input, Text-to-Speech output).
- Intent recognition for queries like 'attendance', 'marks', 'prediction'.""",

    "File Structure": """d:/parentconnect/
- app.py: Main Flask application entry point.
- models.py: Machine Learning logic (PredictiveModel class).
- chatbot.py: Chatbot logic (Intent matching).
- requirements.txt: Python dependencies.
- static/js/app.js: Frontend logic.
- templates/: HTML templates for Login and Dashboard.""",

    "API Endpoints": """- / (GET): Login page
- /dashboard (GET): Dashboard page
- /api/login (POST): Authenticate user
- /api/dashboard (GET): Get translated student data
- /api/translations/<lang> (GET): Get UI strings
- /api/chat (POST): Chatbot interaction
- /api/predict (POST): Custom prediction
- /api/tts (POST): Text-to-Speech"""
}

pdf.add_page()
pdf.set_font('Arial', 'B', 16)
pdf.cell(0, 10, 'Complete Project Analysis', 0, 1, 'C')
pdf.ln(10)

pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 5, "Date: February 19, 2026\nCodebase: Parent Eye\nGenerated by: Antigravity AI")
pdf.ln(10)

for title, body in content.items():
    pdf.chapter_title(pdf.section_counter, title)
    pdf.chapter_body(body)
    pdf.section_counter += 1

output_path = os.path.join(os.getcwd(), 'ParentEye_Report.pdf')
pdf.output(output_path, 'F')
print(f"PDF generated: {output_path}")
